### ISSUE TITLE
jekyll-seed maintainer

### ISSUE THREAD

**Issue by kamicut** [developmentseed/jekyll-seed#4]
Right now jekyll-seed is unmaintained. We need to:
1. Figure out if we want to maintain this repo. I defer to @danielfdsilva or @dereklieu  
2. If we do, figure out if we want to update the dependencies (#3)

**Comment by danielfdsilva** [comment]
I'm not sure how much we're using this these days, but I'll take it up.
I'll maintain this update together with the other seeds. If we see it's definitely not being used, we'll deprecate it.

**Comment by kamicut** [comment]
Thanks @danielfdsilva !
